# Generated by Django 4.2.2 on 2023-07-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0003_remove_driver_parent_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="student",
            name="parent_name",
            field=models.CharField(max_length=60, null=True),
        ),
    ]
